# -*- coding: utf-8 -*-
"""Transducer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K7IQ-4urjUiu7KHQFgHDhvBtE0uQQ6mE
"""


# Mealy
class Transducer:
    def __init__(self, states, transitions, initial):
        self.states = states # Estados do Transdutor
        self.transitions = transitions # Conjunto de transições/saída
        self.initial = initial # Estado inicial

    # Função de processamento de moedas
    def step(self, input):
        current_state = self.initial # Estado inicial
        print(f'Initial: {current_state}')
        for coin in input: # Para todo o conjunto de moedas
            match = False # Flag de erro
            # Verifica se existe a transição
            for transition in self.transitions:
                if transition[0] == current_state and transition[2] == coin:
                    print(f'Moeda: {coin}\tEstado: {transition[1]}'\
                          f'\tOutput: {transition[3]}')
                    # Transiciona para o próximo estado
                    current_state = transition[1]
                    match = True
                    break
            # Erro caso a moeda inserida não esteja no escopo
            if not match:
                print('Error')
                return

states = ['0', '25', '50', '75']
initial = '0'
transitions = [
    ['0', '25', 25, 0],
    ['0', '50', 50, 0],
    ['0', '0', 100, 1],
    ['25', '50', 25, 0],
    ['25', '75', 50, 0],
    ['25', '25', 100, 1],
    ['50', '75', 25, 0],
    ['50', '0', 50, 1],
    ['50', '50', 100, 1],
    ['75', '0', 25, 1],
    ['75', '25', 50, 1],
    ['75', '75', 100, 1]
]

# Coins sequence
input = [50, 25, 50, 100, 25, 50, 100]
transducer = Transducer(states, transitions, initial)
transducer.step(input)
